version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
    networks:
      - watchtower-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.jtest
    profiles: ["test"]

networks:
  watchtower-network:
    name: github-watchtower-backend_watchtower_network