version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
    networks:
      - project_network

  test:
    build:
      context: .
      dockerfile: Dockerfile.jtest
    profiles: ["test"]

networks:
  project_network:
    name: watchtower-network